#!/bin/bash
if [ -n "$JENKINS_PORT_8080_TCP_ADDR" ]; then
cat <<EOF >>/etc/nginx/sites-enabled/default
	location /jenkins {
		proxy_pass http://$JENKINS_PORT_8080_TCP_ADDR:8080;
	}
EOF
fi

if [ -n "$GITBUCKET_PORT_8000_TCP_ADDR" ]; then
cat <<EOF >>/etc/nginx/sites-enabled/default
	location /gitbucket {
		proxy_pass http://$GITBUCKET_PORT_8000_TCP_ADDR:8000;
	}
EOF
fi

echo "}" >>/etc/nginx/sites-enabled/default
nginx
